### ISSUE TITLE
BP_Waypointgenerator.uasset missing

### ISSUE THREAD

**Issue by mecastro** [RohitKotiveetil/UnrealEngine--WaypointGenerator#1]
BP_Waypointgenerator.uasset is missing on ue4 4.21.2

**Comment by RohitKotiveetil** [comment]
Hi, the project is built on UE4 4.22 and hence doesn't work on any previous versions. That's probably why you're getting the message.

I'd suggest upgrading to 4.22 or copying the content within blueprints to create similar blueprints in a 4.21 project.
